# Generated by Django 2.1.3 on 2018-11-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('lugar_origen', models.CharField(max_length=30)),
                ('ColorPrimerUniforme', models.CharField(max_length=30)),
                ('ColorSegundoUniforme', models.CharField(max_length=30)),
                ('numeroDeJugadores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('lugar', models.CharField(max_length=60)),
                ('premio', models.CharField(max_length=60)),
                ('incripcion', models.IntegerField()),
                ('equipos', models.ManyToManyField(through='aplicacion.Competicion', to='aplicacion.Equipo')),
            ],
        ),
        migrations.AddField(
            model_name='competicion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Equipo'),
        ),
        migrations.AddField(
            model_name='competicion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Torneo'),
        ),
    ]
