# Generated by Django 2.1.3 on 2018-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='descripcion',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
