# Generated by Django 2.1.3 on 2018-11-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_competicion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicion',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='competicion',
            name='torneo',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='equipos',
        ),
        migrations.DeleteModel(
            name='Competicion',
        ),
    ]
