# Generated by Django 2.1.3 on 2018-11-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20181103_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=60, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Torneo')),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='equipos',
            field=models.ManyToManyField(through='aplicacion.Competicion', to='aplicacion.Equipo'),
        ),
    ]
